services:
  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
  api:
    command: bun dev
    build:
      target: dev
    develop:
        watch:
          - action: rebuild
            path: package.json
          - action: sync
            path: src
            target: /usr/src/app/src
    environment:
      - NODE_ENV=development
