version: '3'

services:
  redis:
    image: "redis:alpine"
  api:
    build: .
    command: bun start
    depends_on:
      - redis
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: src
          target: /usr/src/app/src
