version: '3'

services:
  redis:
    image: "redis/redis-stack-server"
  api:
    build:
      context: .
      target: prod
    command: bun start
    init: true
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
