version: '3'

services:
  redis:
    image: "redis:alpine"
  api:
    build: .
    command: bun start
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
